@echo off
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\doc-list.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\doc-list.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\doc-editor.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\doc-editor.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\trash.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\trash.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\trash-header.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\trash-header.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\trash-stats.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\trash-stats.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\trash-layout.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\trash-layout.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\trash-table.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\trash-table.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\trash-responsive.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\trash-responsive.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\utility-pages.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\docs\css\utility-pages.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\login\login.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\login\css\login.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\forms\form-list.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\forms\css\form-list.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\forms\form-editor.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\forms\css\form-editor.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\forms\form-submissions.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\forms\css\form-submissions.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\reviews\share-review.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\reviews\css\share-review.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\invites\invite.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\invites\css\invite.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\admin\admin-layout.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\admin\css\admin-layout.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\danger\danger.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\danger\css\danger.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\register\register.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\register\css\register.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\settings\settings.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\settings\css\settings.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\settings\security-center.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\settings\css\security-center.css"
move "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\settings\settings-storage.css" "D:\desktop\bixu\js\chensdoc-claude\apps\admin\src\pages\settings\css\settings-storage.css"
echo Done!